### ISSUE TITLE
Broken table

### ISSUE THREAD

**Issue by GuillaumeGomez** [raphlinus/pulldown-cmark#127] opened 2018-03-05 15:04 UTC
with the current code:

```rust
//!     | Non-terminal | Usage                                                      |
//!     |--------------|------------------------------------------------------------|
//!     | `(e)`        | matches `e`                                                |
//!     | `e1 ~ e2`    | matches the sequence `e1` `e2`                             |
//!     | `e1 | e2`    | matches either `e1` or `e2`                                |
//!     | `e*`         | matches `e` zero or more times                             |
//!     | `e+`         | matches `e` one or more times                              |
//!     | `e{n}`       | matches `e` exactly `n` times                              |
//!     | `e{, n}`     | matches `e` at most `n` times                              |
//!     | `e{n,} `     | matches `e` at least `n` times                             |
//!     | `e{m, n}`    | matches `e` between `m` and `n` times inclusively          |
//!     | `e?`         | optionally matches `e`                                     |
//!     | `&e`         | matches `e` without making progress                        |
//!     | `!e`         | matches if `e` doesn't match without making progress       |
//!     | `push(e)`    | matches `e` and pushes it's captured string down the stack |
```

At this line more precisely:

```rust
//!     | `e1 | e2`    | matches either `e1` or `e2`                                |
```

The `|` is taken as a column ending and not just a character which breaks the rendering.

**Comment by Fierthraix** [comment] 2018-03-06 05:13
I found the same problem here: https://github.com/rust-lang-nursery/mdBook/issues/637

Here's the cross post

<hr />

## Problem
You have a table that you want to look like this

<table><thead><tr><td>           Regex             </td><td>     Matches     </td></tr></thead><tr><td><code>foo-(1|[3-5])|bar-([39]|39)</code></td><td><code>foo-1</code>, <code>bar-39</code></td></tr></table>

It has some code with pipes in it.

### Attempt 1

Your initial solution is just to put the code in the table

```markdown
|           Regex             |     Matches     |
|-----------------------------|-----------------|
|`foo-(1|[3-5])|bar-([39]|39)`|`foo-1`, `bar-39`|
```

which actually renders as:

<table><thead><tr><td>           Regex             </td><td>     Matches     </td></tr></thead><tr><td>`foo-(1</td><td>[3-5])</td><td>bar-([39]</td><td>39)`</td><td><code>foo-1</code>, <code>bar-39</code></td></tr></table>

because every pipe gets interpreted as a table column. 

### Attempt 2
The next logical step is to add an escape `\` before the `|`
```markdown
|           Regex             |     Matches     |
|-----------------------------|-----------------|
|`foo-(1\|[3-5])\|bar-([39]\|39)`|`foo-1`, `bar-39`|
```

Which escapes the `|`, but also magically renders your escape `\`!

<table><thead><tr><td>           Regex             </td><td>     Matches     </td></tr></thead><tr><td><code>foo-(1\|[3-5])\|bar-([39]\|39)</code></td><td><code>foo-1</code>, <code>bar-39</code></td></tr></table>

This prevents the pipe from being interpreted as a part of the table, but prints the backslash for some reason! This makes it seem like that with pure markdown there is no way to escape the pipe without printing the escape character.

### Using HTML

You decide to put inline HTML and replace the backtick with a `<code>` tag (sans escape backslashes on the pipe)

```markdown
|           Regex             |     Matches     |
|-----------------------------|-----------------|
|<code>foo-(1|[3-5])|bar-([39]|39)</code>|`foo-1`, `bar-39`|
```
which renders as:

<table><thead><tr><td>           Regex             </td><td>     Matches     </td></tr></thead><tr><td><code>foo-(1</td><td>[3-5])</td><td>bar-([39]</td><td>39)</code></td><td><code>foo-1</code>, <code>bar-39</code></td></tr></table>

This doesn't print the backticks like in the first attempt, and actually shades the first cell as being code. The problem being that we now have pipes making new columns again! 
This is the only example so far that works as we would've expected for a parser that doesn't search for the closing tag.

### `<code>` tag with escape backslash

Using HTML was an improvement, so what if we try out the escape backslashes again?

```markdown
|           Regex             |     Matches     |
|-----------------------------|-----------------|
|<code>foo-(1\|[3-5])\|bar-([39]\|39)</code>|`foo-1`, `bar-39`|
```

<table><thead><tr><td>           Regex             </td><td>     Matches     </td></tr></thead><tr><td><code>foo-(1\|[3-5])\|bar-([39]\|39)</code></td><td><code>foo-1</code>, <code>bar-39</code></td></tr></table>

Success! Using `<code>` tags in conjunction with escape backslashes produces the desired result.

### Rendering without inline code
To constrast this with how markdown renders outside of code tags, using an escape backslash works exactly as expected:

```markdown
|           Regex             |     Matches     |
|-----------------------------|-----------------|
|foo-(1\|[3-5])\|bar-([39]\|39)|`foo-1`, `bar-39`|
```

<table><thead><tr><td>           Regex             </td><td>     Matches     </td></tr></thead><tr><td>foo-(1\|[3-5])\|bar-([39]\|39)</td><td><code>foo-1</code>, <code>bar-39</code></td></tr></table>

My guess for this is that when a backtick is detected in a table, the table mode searching for unescaped pipes doesn't switch off for unescaped backslashes, leading to the results above.

## Expected Results:
You would expect that when you insert a code backtick that everything between the <code>\`  \`</code> isn't affected by what context it is in (in this case a table). This is desirable because it is frustrating to have to be aware that what characters you have to escape depends on what kind of structure you already have.

If this is not realizable/goes against the current standard then at the very least I think that using the escape backslash before a pipe should **not** render.

**Comment by Fierthraix** [comment] 2018-03-06 05:15
Code required to reproduce (this is a rust file saved as a .txt file)
[main.txt](https://github.com/google/pulldown-cmark/files/1783613/main.txt)

**Comment by marcusklaas** [comment] 2019-03-13 16:34
This is still an issue on current master. I'll try to update the #128 for the current codebase.

**Comment by marcusklaas** [comment] 2019-03-13 18:43
This seems to be valid behaviour according to the [GFM spec](https://github.github.com/gfm/#example-193), actually. You need to escape a pipe inside tables, even if it follows a backtick.

**Closed by marcusklaas** 2019-03-13 18:43 UTC
