### ISSUE TITLE
Parsing link ref. defs. is slow

### ISSUE THREAD

**Issue by mity** [raphlinus/pulldown-cmark#322] opened 2019-05-13 16:03 UTC
After the merge of PR #281, parsing link reference definitions is slow.

It seems to grow in the linear fashion which is fine, but still, take a look at these times:

```
$ time python3 -c 'print("[a]: u\n" * 40000)' | ./pulldown-cmark >/dev/null 2>/dev/null
real    0m1.134s
user    0m0.125s
sys     0m1.000s

$ time python3 -c 'print("xxxxxx\n" * 40000)' | ./pulldown-cmark >/dev/null 2>/dev/null
real    0m0.058s
user    0m0.016s
sys     0m0.047s

$ time python3 -c 'print("*xxxx*\n" * 40000)' | ./pulldown-cmark >/dev/null 2>/dev/null
real    0m0.074s
user    0m0.047s
sys     0m0.016s
```

**Comment by mity** [comment] 2019-05-13 16:11
cc @marcusklaas

**Comment by raphlinus** [comment] 2019-05-13 16:15
I confirm this is a performance regression from 0.5.0. Doing a touch of digging...

**Comment by raphlinus** [comment] 2019-05-13 16:17
The performance slowdown seems to be caused by the `dbg!` in scanners.rs. Whew, this is known and we will get rid of it before releasing.

**Comment by marcusklaas** [comment] 2019-05-13 16:52
Fixed now!

**Closed by marcusklaas** 2019-05-13 16:52 UTC
