### ISSUE TITLE
Unintuitive positions reported for links

### ISSUE THREAD

**Issue by Michael-F-Bryan** [raphlinus/pulldown-cmark#378] opened 2019-07-19 17:37 UTC
I'm rewriting part of [mdbook-linkcheck](https://crates.io/crates/mdbook-linkcheck) to give better feedback, and a big part of this relies on `Parser::get_offset()` to determine a link's exact location in the source text.

The offsets for a `Start` or `End` link tag seem a bit funny. I'm getting `18..19` for both `Start` and `End`, when I know the link stretches across (roughly) `18..49`.

# Steps to Reproduce

The following code:

```rust
#[test]
fn unintuitive_link_locations() {
    let src = "This is a link to [nowhere](http://doesnt.exist/)";

    for (ev, range) in Parser::new(src).into_offset_iter() {
        println!("{:?} @ {:?}", ev, range);
    }

    panic!();
}
```

results in this output:

```
Start(Paragraph) @ 0..49
Text(Borrowed("This is a link to ")) @ 0..18
Start(Link(Inline, Borrowed("http://doesnt.exist/"), Borrowed(""))) @ 18..19
Text(Borrowed("nowhere")) @ 19..26
End(Link(Inline, Borrowed("http://doesnt.exist/"), Borrowed(""))) @ 18..19
End(Paragraph) @ 0..49
```

# Expected

I was expecting either

- `Start(Link(..)) @ 18..49` and `End(Link(..)) @ 18..49` - i.e. both get the range for the full `[..](..)` link like `Paragraph`, or
- `Start(Link(..) @ 18..19` and `End(Link(..)) @ 28..49` - i.e. the opening `[` and the trailing `("http://doesnt.exist/")`

**Comment by marcusklaas** [comment] 2019-07-19 17:40
Yup, that's a bug. Thanks for reporting it!On Jul 19, 2019 19:37, Michael Bryan <notifications@github.com> wrote:I'm rewriting part of mdbook-linkcheck to give better feedback, and a big part of this relies on Parser::get_offset() to determine a link's exact location in the source text.
The offsets for a Start or End link tag seem a bit funny. I'm getting 18..19 for both Start and End, when I know the link stretches across (roughly) 18..49.
Steps to Reproduce
The following code:
#[test]
fn unintuitive_link_locations() {
    let src = "This is a link to [nowhere](http://doesnt.exist/)";

    for (ev, range) in Parser::new(src).into_offset_iter() {
        println!("{:?} @ {:?}", ev, range);
    }

    panic!();
}
results in this output:
Start(Paragraph) @ 0..49
Text(Borrowed("This is a link to ")) @ 0..18
Start(Link(Inline, Borrowed("http://doesnt.exist/"), Borrowed(""))) @ 18..19
Text(Borrowed("nowhere")) @ 19..26
End(Link(Inline, Borrowed("http://doesnt.exist/"), Borrowed(""))) @ 18..19
End(Paragraph) @ 0..49

Expected
I was expecting either
Start(Link(..)) @ 18..49 and End(Link(..)) @ 18..49 - i.e. both get the range for the full [..](..) link like Paragraph, orStart(Link(..) @ 18..19 and End(Link(..)) @ 28..49 - i.e. the opening [ and the trailing ("http://doesnt.exist/")

**Comment by Michael-F-Bryan** [comment] 2019-07-19 18:00
@marcusklaas, I'd be happy to work on this if it's a trivial fix and you can point me in the right direction.

I'm guessing it's got something to do with [this section](https://github.com/raphlinus/pulldown-cmark/blob/b8e449c7134e67f88b1f1377dffc484b22d76d8c/src/parse.rs#L2611-L2621) of `Parser::next()`. Potentially something around nested tree nodes?

**Comment by marcusklaas** [comment] 2019-07-19 19:34
That piece of code is simply walking the tree and generating events from the node details. It's more likely that the problem is in the creation of the Link node and specifically that we forget to set the node's end. That's done [in this block](https://github.com/raphlinus/pulldown-cmark/blob/master/src/parse.rs#L2048-L2071).

Thanks for giving it a try!

**Comment by marcusklaas** [comment] 2019-07-23 17:10
Fixed now!

**Closed by marcusklaas** 2019-07-23 17:10 UTC
