### ISSUE TITLE
Slow (but linear) parsing of "[{}]:\\a[{}]:\\a..."[..len()-1]

### ISSUE THREAD

**Issue by oberien** [raphlinus/pulldown-cmark#287] opened 2019-05-02 10:28 UTC
When parsing the repetition `"[{}]:\\a..."`, the parser is fast. However, if the very last byte is omitted (the trailing "a" of the resulting string, not the repetition), such that you get `"[{}]:\\a...[{}]:\\"`, the parser is tens of thousand times slower. The following table contains the respective parsing time of pulldown-cmark for n*25KB input bytes.

with trailing a<br>(noisy due to small values) | without trailing a
--- | ---
426ns | 1.058801ms
243ns | 2.12739ms
172ns | 3.516731ms
175ns | 4.357934ms
327ns | 5.63836ms
285ns | 6.770627ms
330ns | 7.643213ms
223ns | 8.82521ms
194ns | 9.992497ms
276ns | 10.939186ms

**Comment by oberien** [comment] 2019-05-02 10:35
There seem to be several other inputs with the same behaviour. Should I report them as well, or is this somewhat expected behaviour?

**Comment by marcusklaas** [comment] 2019-05-02 14:11
Something weird is definitely going on here.. but I'm more confused by the extremely fast parse on the left column. Parsing 250kB in < 300ns? That seems implausible. You'd almost think the closing quote is escaped?

I'll try to reproduce this locally.

**Comment by marcusklaas** [comment] 2019-05-02 14:35
Ok, this is what I get locally:
```
running 2 tests
test to_html::weird_refdefs1                   ... bench:      38,066 ns/iter (+/- 1,152)
test to_html::weird_refdefs2                   ... bench:     802,627 ns/iter (+/- 39,684
```
where `weird_refdefs1` has the trailing a and `weird_refdefs2` does not.

It appears the one with the trailing a is somehow considered a valid reference definition, and the other is parsed as regular text. Since it contains lots of special bytes (`[`, `]` and `\\`) it has to allocate lots of nodes in the tree. I presume that is what's making it slow.

**Comment by oberien** [comment] 2019-05-02 15:00
I just ended up at the same conclusion. With the trailing `a`, it's interpreted as
```[{}]:\a
[{}]:\a[{}]:...
     ^^^^^^^^^^ reference url
^^^^^   reference definition
 ^^     label `{}`
```

This means that it scans a single reference definition with a long url. But parsing the long url is literally iterating over it a single time until `EOF` or `\n` is found. This explains the very fast execution speed of a few hundred ns.

Without the trailing `a`, it's not parsed as a valid reference definition by pulldown-cmark. My guess would be, that the parser discards the `\n` / `EOF` while trying to find the escaped character.

The commonmark demo *does* detect it as reference definition without the trailing `a`:

```md
Link to [foo][{}]

[{}]:\[{}]:\
```
gets converted to

```html
<p>Link to <a href="%5B%7B%7D%5D:%5C">foo</a></p>
```

So this actually seems like a bug in pulldown-cmark?!

**Comment by mity** [comment] 2019-05-02 15:29
> So this actually seems like a bug in pulldown-cmark?!

IDK. On one side, `\`, when not followed by a punctuation char or end-of-line, is just literal `\`, which is a valid char for URL.

On the other side, here the `\` is followed by EOF. So the answer depends on the following:

1. Does `\` followed by EOF form a hard break as when it is followed by `\n` or not? 
   (If yes, see (2). If no, it should be ref. link def. and `\` is literal char in the URL.)

2. Can link ref. def. be ended with a hard break instead of a soft break? 
   (My intuition is "no" but...) 

...imho none of these question is covered by CommonMark specs.

**Comment by mity** [comment] 2019-05-03 19:50
So, given the https://github.com/commonmark/commonmark-spec/issues/583, as of the current specs wording, it is likely a bug in implementation. The final `\` should be part of the ref. def. URL.

**Comment by marcusklaas** [comment] 2019-05-04 08:59
Thanks for verifying this!

**Closed** 2019-05-13 14:29 UTC
