### ISSUE TITLE
Panic for unicode character in markdown

### ISSUE THREAD

**Issue by terhechte** [raphlinus/pulldown-cmark#448] opened 2020-06-07 09:57 UTC
I ran into a panic with the following markdown string. I didn't format it because I wasn't sure if that'd still trigger the bug. However, pasting it and running pulldown-cmark panics.

The issue seems to be the `—` which is inserted automatically by macOS in many apps when the user types `---`. 

``` rs
let md = "# Chocolate Bean **Varieties**\n\n\n---\n\n![](737DAC76-AB04-48B2-ACCF-03A73EA35539.jpg)\n\n# Forastero\n\n- The most widely cul\n- 90 - 90% of world\n\n- :: —";
```

I tried to debug it but it was rather complex due to being a unicode issue and so on. My current solution around this is to use panic unwinding and catching the panic which is not optimal but at least the whole app doesn't crash when macOS replaces a character.

**Comment by marcusklaas** [comment] 2020-06-07 12:22
Sending a big thank your way for reporting this. Panics are clearly no bueno. I'll have a look at this shortly!

**Comment by marcusklaas** [comment] 2020-06-08 12:46
Hmmm, I cannot reproduce this with the string you posted. What version of pulldown are you on?

**Comment by terhechte** [comment] 2020-06-08 13:16
I ran into this issue some weeks ago, so I didn't test with the most recent version. I just forgot to report it here. Sorry for not testing it again before reporting it! I'm sadly on a fork because I need [this in my pulldown-cmark usage](https://github.com/raphlinus/pulldown-cmark/pull/420). So please ignore this issue right now, I'll look into it again to make sure it is not something I accidentally introduced into my fork.

Sorry!

**Comment by marcusklaas** [comment] 2020-07-03 11:30
No worries. I'll close this for now, but please reopen if you find a reproducible case on the latest release!

**Closed by marcusklaas** 2020-07-03 11:30 UTC
