### ISSUE TITLE
Tables: | cannot be escaped in code

### ISSUE THREAD

**Issue by vojtechkral** [raphlinus/pulldown-cmark#639] opened 2023-04-16 22:02 UTC
The following md

```md
| Foo    | Bar |
| ------ | --- |
| **\|** | Bar |
| `\|`   | Bar |
```

renders as this according to [GFM spec](https://github.github.com/gfm/#tables-extension-):

| Foo    | Bar |
| ------ | --- |
| **\|** | Bar |
| `\|`   | Bar |

in pulldown-cmark the backslash seems to be applied as escaping the `|`, but it's not removed from the output when in inline code, the table renders as:

| Foo    | Bar |
| ------ | --- |
| **\|** | Bar |
| `\\|`   | Bar |

(Ran into this in mdBook.)

**Comment by ehuss** [comment] 2023-04-16 22:31
I believe this is a duplicate of #356. There are a few workarounds discussed in there.

**Comment by vojtechkral** [comment] 2023-04-16 23:25
Ah sorry I did try searching but apparently didn't search enough. Yup, the `<code>` workaround is what I'm using atm...

**Closed** 2023-04-16 23:26 UTC
