### ISSUE TITLE
Request for abbreviations/acronyms

### ISSUE THREAD

**Issue by heitorPB** [raphlinus/pulldown-cmark#527] opened 2021-05-19 02:35 UTC
I'like to request support for abbreviations.

Abbreviations and/or acronyms (in HTML with the `<abbr>` tag) are not part of CommonMark neither GFM, but they are very useful.

Kramdown docs have a [nice example about it](https://kramdown.gettalong.org/quickref.html#abbreviations).

**Comment by marcusklaas** [comment] 2021-05-25 16:26
This is a duplicate of https://github.com/raphlinus/pulldown-cmark/issues/5, so I will close this and respond there instead.

**Closed by marcusklaas** 2021-05-25 16:26 UTC
