### ISSUE TITLE
[Question] How to get img alt?

### ISSUE THREAD

**Issue by yumetodo** [raphlinus/pulldown-cmark#394] opened 2019-09-01 15:46 UTC
At first, to get img alt text, I just get 3rd argument of Tag::Image like below:

````rust
#[allow(dead_code)]
fn example2(markdown_input: &str) -> Vec<String> {
    // Set up options and parser. Strikethroughs are not part of the CommonMark standard
    // and we therefore must enable it explicitly.
    let mut opts = Options::empty();
    opts.insert(Options::ENABLE_TABLES);
    opts.insert(Options::ENABLE_FOOTNOTES);
    opts.insert(Options::ENABLE_STRIKETHROUGH);
    opts.insert(Options::ENABLE_TASKLISTS);
    let parser = Parser::new_ext(markdown_input, opts);
    let mut re: Vec<String> = Vec::new();
    for event in parser.clone() {
        match event {
            Event::End(Tag::Image(link_type, url, alt)) => {
                println!("{:?}, {:?}, {:?}", link_type, url, alt);
                re.push(alt.into_string());
            }
            _ => ()
        }
    }
    re
}
#[cfg(test)]
mod tests {

    #[test]
    fn example2() {
        let markdown_input = r"# arikitari

![1](1.png)

![cpp](D3T3cG6U0AAd0Zn.jpg)

![atgtheiwa1](D5iuwp0W4AEm1bi.jpg)

![atgtheiwa2](D5jwkn7XsAABJvV.jpg)

![IR](IR.jpg)
```markdown
![2][2.png]
```
";
        let re = super::example2(markdown_input);
        print!("{:?}", re);
        let test = re.iter().eq(&["1", "cpp", "atgtheiwa1", "atgtheiwa2", "IR"]) ;
        assert!(test);
    }
}

````

However, that returns empty string.

```
test tests::example2 ... FAILED

failures:

---- tests::example2 stdout ----
Inline, Borrowed("1.png"), Borrowed("")
Inline, Borrowed("D3T3cG6U0AAd0Zn.jpg"), Borrowed("")
Inline, Borrowed("D5iuwp0W4AEm1bi.jpg"), Borrowed("")
Inline, Borrowed("D5jwkn7XsAABJvV.jpg"), Borrowed("")
Inline, Borrowed("IR.jpg"), Borrowed("")
["", "", "", "", ""]thread 'tests::example2' panicked at 'assertion failed: test', src\lib.rs:179:9
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace.


failures:
    tests::example2
```

How should I do to get that?

I suspect around `scan_inline_link`...

https://github.com/raphlinus/pulldown-cmark/blob/d46259206d2d1129c8ac85c56a0de22b0aef6234/src/scanners.rs#L915-L945

**Comment by marcusklaas** [comment] 2019-09-02 16:17
So this is a bit weird, but images are _tags_ in pulldown_cmark, which means that they contain other events. This is understably confusing, as this isn't true for html images.

The alt text you are looking for is contained in the image tag. For example, the snippet `![*a*](b "c")` will produce the following events:
```
0: Start(Paragraph)
0: Start(Image(Inline, Borrowed("b"), Inlined(InlineStr { inner: [99, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1] })))
2: Start(Emphasis)
3: Text(Borrowed("a"))
4: End(Emphasis)
5: End(Image(Inline, Borrowed("b"), Inlined(InlineStr { inner: [99, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1] })))
13: End(Paragraph)
```
The value you were expecting to be the alt is actually the image's title!

Hope this clears things up. We may want to reconsider this design at some point at make images atoms to prevent such confusion.

**Comment by mity** [comment] 2019-09-03 18:27
> We may want to reconsider this design at some point and make images atoms to prevent such confusion.

The problem is the contents of the Markdown image can contain nested inline Markdown elements. [It's true that the CommonMark specs recommends to ignore them them for HTML output](https://spec.commonmark.org/0.29/#example-572) but other kinds of renderers might need/want to use them.

**Comment by marcusklaas** [comment] 2019-09-04 11:29
Thanks for the excellent considerations as always @mity. I suppose the current design is actually sensible. Closing this issue as the main question should be answered. If not, feel free to reopen!

**Closed by marcusklaas** 2019-09-04 11:29 UTC

**Comment by yumetodo** [comment] 2019-09-05 16:05
Thank you for your answers. As a result, based on CommonMark0.29 Spec example 572, to get img alt, I need to concat all `Text` event strings, isn't it?

> Hope this clears things up. We may want to reconsider this design at some point and make images atoms to prevent such confusion.

I want more documentation around below:

1. https://docs.rs/pulldown-cmark/0.5.3/pulldown_cmark/enum.Tag.html#variant.Image  
    > the third is a title

    I want example to tell users what is titile
2. https://docs.rs/pulldown-cmark/0.5.3/pulldown_cmark/enum.Event.html#variant.Start
    Also I want example like https://github.com/raphlinus/pulldown-cmark/issues/394#issuecomment-527197423 to tell the deferences between `Start` and `End` event.
