### ISSUE TITLE
The lifetimes on BrokenLinkCallback are wrong

### ISSUE THREAD

**Issue by jyn514** [raphlinus/pulldown-cmark#509] opened 2020-12-08 16:03 UTC
Here is a simple callback which marks every link as working:

```rust
fn callback<'a>(link: BrokenLink<'a>) -> Option<(CowStr<'a>, CowStr<'a>)> {
    Some(("#".into(), link.reference.into()))
}
```

On its own, it typechecks fine. Unfortunately, this doesn't work with `Parser::with_broken_link_callback`:

```rust
fn f(txt: &str) {
    for _ in Parser::new_with_broken_link_callback(txt, Options::empty(), Some(&mut callback)) {
    }
}
```
```
error: implementation of `FnOnce` is not general enough
   --> src/lib.rs:8:80
    |
8   |       for _ in Parser::new_with_broken_link_callback(txt, Options::empty(), Some(&mut callback)) {
    |                                                                                  ^^^^^^^^^^^^^ implementation of `FnOnce` is not general enough
    | 
   ::: /home/joshua/.local/lib/rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/core/src/ops/function.rs:219:1
    |
219 | / pub trait FnOnce<Args> {
220 | |     /// The returned type after the call operator is used.
221 | |     #[lang = "fn_once_output"]
222 | |     #[stable(feature = "fn_once_output", since = "1.12.0")]
...   |
227 | |     extern "rust-call" fn call_once(self, args: Args) -> Self::Output;
228 | | }
    | |_- trait `FnOnce` defined here
    |
    = note: `for<'a> fn(pulldown_cmark::BrokenLink<'a>) -> Option<(pulldown_cmark::CowStr<'a>, pulldown_cmark::CowStr<'a>)> {callback}` must implement `FnOnce<(pulldown_cmark::BrokenLink<'_>,)>`
    = note: ...but `FnOnce<(pulldown_cmark::BrokenLink<'_>,)>` is actually implemented for the type `for<'a> fn(pulldown_cmark::BrokenLink<'a>) -> Option<(pulldown_cmark::CowStr<'a>, pulldown_cmark::CowStr<'a>)> {callback}`

error: aborting due to previous error
```
The issue is that `BrokenLinkCallback` is typed as having the same lifetime as its outputs: https://github.com/raphlinus/pulldown-cmark/blob/e97974b8d76195c953f0d427e8725ef9ad1a0c17/src/parse.rs#L1270
That means that the callback can't e.g. be passed to two different parsers, because the first call will fix a set lifetime:

```rust
 fn f(txt: &str) {
    let mut callback = |link: BrokenLink<'_>| -> Option<(CowStr<'_>, CowStr<'_>)> {
        Some(("#".into(), link.reference.to_owned().into()))
    };

    for _ in Parser::new_with_broken_link_callback(txt, Options::empty(), Some(&mut callback)) {
    }

    for _ in Parser::new_with_broken_link_callback(txt, Options::empty(), Some(&mut callback)) {
    }
}
```
```
error[E0499]: cannot borrow `callback` as mutable more than once at a time
  --> src/lib.rs:11:80
   |
8  |     for _ in Parser::new_with_broken_link_callback(txt, Options::empty(), Some(&mut callback)) {
   |                                                                                ------------- first mutable borrow occurs here
...
11 |     for _ in Parser::new_with_broken_link_callback(txt, Options::empty(), Some(&mut callback)) {
   |                                                                                ^^^^^^^^^^^^^
   |                                                                                |
   |                                                                                second mutable borrow occurs here
   |                                                                                first borrow later used here
```

The fix I was thinking of was something like this:

```diff
diff --git a/src/parse.rs b/src/parse.rs
index d6388b1..bccd68c 100644
--- a/src/parse.rs
+++ b/src/parse.rs
@@ -129,12 +129,12 @@ pub struct BrokenLink<'a> {
 }
 
 /// Markdown event iterator.
-pub struct Parser<'a> {
-    text: &'a str,
+pub struct Parser<'input, 'callback: 'input> {
+    text: &'input str,
     options: Options,
     tree: Tree<Item>,
-    allocs: Allocations<'a>,
-    broken_link_callback: BrokenLinkCallback<'a>,
+    allocs: Allocations<'input>,
+    broken_link_callback: BrokenLinkCallback<'callback>,
     html_scan_guard: HtmlScanGuard,
 
     // used by inline passes. store them here for reuse
@@ -1266,8 +1267,8 @@ pub(crate) struct HtmlScanGuard {
     pub declaration: usize,
 }
 
-pub type BrokenLinkCallback<'a> =
-    Option<&'a mut dyn FnMut(BrokenLink) -> Option<(CowStr<'a>, CowStr<'a>)>>;
+pub type BrokenLinkCallback<'b> =
+    Option<&'b mut dyn for<'a> FnMut(BrokenLink<'a>) -> Option<(CowStr<'a>, CowStr<'a>)>>;
 
 /// Markdown event and source range iterator.
 ///
```
This does two things:
1. Separates the lifetime of the link from the lifetime of the callback (by changing `&'a FnMut() -> &'a str` to `&'b for<'a> FnMut() -> &'a str`).
2. Separates the lifetime of the link from the lifetime of the link (by adding a new `'callback` lifetime).

Unfortunately, this uncovers that the change *can't* work:

```
error[E0597]: `link_label` does not live long enough
   --> src/parse.rs:457:64
    |
145 |   impl<'a, 'b> Parser<'a, 'b> {
    |        -- lifetime `'a` defined here
...
450 |                                       .or_else(|| {
    |                                                -- value captured here
...
457 |                                                       reference: link_label.as_ref(),
    |                                                                  ^^^^^^^^^^ borrowed value does not live long enough
...
460 | /                                                 callback(broken_link).map(|(url, title)| {
461 | |                                                     (link_type.to_unknown(), url, title)
462 | |                                                 })
    | |__________________________________________________- returning this value requires that `link_label` is borrowed for `'a`
...
503 |                               }
    |                               - `link_label` dropped here while still borrowed
```

The issue is that `link_label` is only alive for the duration for the length of a single loop iteration, *not* the lifetime of the input. Even though it's parameterized by a lifetime `'input`, it has a [`Box` variant](https://docs.rs/pulldown-cmark/0.8.0/pulldown_cmark/enum.CowStr.html#variant.Boxed), so if it gets dropped the compiler has to conservatively assume the entire link is invalid.

I don't have a solution for this, I think it will require a redesign of the parser. But people are running into this in the real world: https://github.com/rust-lang/rust/pull/79781/files#r537769663

**Comment by jyn514** [comment] 2020-12-08 16:16
Actually, I think this will work:

```diff
diff --git a/src/parse.rs b/src/parse.rs
index d6388b1..231fb95 100644
--- a/src/parse.rs
+++ b/src/parse.rs
@@ -125,16 +125,16 @@ impl<'a> Default for ItemBody {
 pub struct BrokenLink<'a> {
     pub span: std::ops::Range<usize>,
     pub link_type: LinkType,
-    pub reference: &'a str,
+    pub reference: CowStr<'a>,
 }
 
 /// Markdown event iterator.
@@ -453,7 +454,7 @@ impl<'a> Parser<'a> {
                                                 let broken_link = BrokenLink {
                                                     span: (self.tree[tos.node].item.start)..end,
                                                     link_type,
-                                                    reference: link_label.as_ref(),
+                                                    reference: link_label,
                                                 };
 
                                                 callback(broken_link).map(|(url, title)| {
```

**Comment by marcusklaas** [comment] 2020-12-08 16:30
Thanks for opening this. The lifetimes for the callback is something we've already struggled with quite a bit, and this issue shows that it may not be solved completely yet.

> That means that the callback can't e.g. be passed to two different parsers, because the first call will fix a set lifetime:
```
error[E0499]: cannot borrow `callback` as mutable more than once at a time
  --> src/lib.rs:11:80
   |
8  |     for _ in Parser::new_with_broken_link_callback(txt, Options::empty(), Some(&mut callback)) {
   |                                                                                ------------- first mutable borrow occurs here
...
11 |     for _ in Parser::new_with_broken_link_callback(txt, Options::empty(), Some(&mut callback)) {
   |                                                                                ^^^^^^^^^^^^^
   |                                                                                |
   |                                                                                second mutable borrow occurs here
   |                                                                                first borrow later used here
```

I haven't dug too deeply yet, but I'm surprised your first example doesn't compile. Especially the bit `first borrow later used here`: that doesn't seem right. The first borrow should end after the initial loop, right?

**Comment by jyn514** [comment] 2020-12-08 16:34
> The first borrow should end after the initial loop, right?

It should, but it does not, because `BrokenLinkCallback` ties the lifetime of the callback to the lifetime of the outputs. Since the outputs are dropped in the loop (`for _`), the callback can't be used after the loop ends.

**Comment by jyn514** [comment] 2020-12-08 16:34
I plan to make a PR fixing this shortly, FYI

**Comment by marcusklaas** [comment] 2020-12-08 16:35
Okay, looking forward to that. I will try to understand more deeply in the meantime.

**Comment by mitsuhiko** [comment] 2020-12-10 11:47
I just ran into the same issue. I'm wondering if it wouldn't make sense to convert this thing into a trait instead of a callback and parametrize the parser for it. That would make this a lot more flexible than juggling with the callback.

**Comment by jyn514** [comment] 2020-12-10 13:13
@mitsuhiko can you expqb

**Comment by jyn514** [comment] 2020-12-10 13:13
I hate GitHub mobile 😠

**Comment by mitsuhiko** [comment] 2020-12-12 19:32
@jyn514 for my use cases I need to query a data structure to perform the lookup. This means that currently to use this I need to borrow something mutably which just generally is unnecessarily complex. In fact I find even with the fix from the PR this to be an unnecessarily complex API.

**Comment by marcusklaas** [comment] 2020-12-12 22:11
Armin, could you elaborate why you'd need a mutable borrow for that? Couldn't you just use a immutable reference to the data structure to perform the lookup?

**Comment by jyn514** [comment] 2020-12-12 22:50
@marcusklaas I think they mean they need to pass a mutable reference to the callback instead of passing it by value: https://github.com/rust-lang/rust/blob/7efc097c4fe6e97f54a44cee91c56189e9ddb41c/src/librustdoc/html/markdown.rs#L948

**Comment by marcusklaas** [comment] 2020-12-12 22:51
Oh right, that makes sense. Could that be resolved by using generics?

**Comment by jyn514** [comment] 2020-12-12 22:52
I think so, if you took `F: FnMut()` instead of `&mut dyn FnMut()`.

**Comment by marcusklaas** [comment] 2020-12-12 22:54
Interesting. That makes for a good argument to use generics. I'll have to investigate how large the binary size cost is whenever different callbacks are used.

**Comment by mitsuhiko** [comment] 2020-12-13 12:10
Basically what @jyn514 mentioned. In the example linked the problem is largely avoided by the callback being created locally and the iterator from the parser being held alive until until the end of the scope. If one wants to create a `parse(source) -> Iterator` function instead that becomes a lot more complex.

**Comment by jyn514** [comment] 2020-12-13 13:52
> If one wants to create a parse(source) -> Iterator function instead that becomes a lot more complex.

@mitsuhiko I would expect that to be fixed by #510. I think 'generics make this conceptually simpler' is a good take but I would expect any code you wrote to work as is with 510 - do you mind trying it out?

**Closed** 2020-12-14 18:40 UTC

**Comment by mitsuhiko** [comment] 2020-12-20 00:12
@jyn514 i will give it a try, but independently also ran into #508 :(

**Comment by Veykril** [comment] 2021-03-29 19:39
Quick question, as the lifetime fixes are pushed to the master branch, is there something blocking a next release containing these fixes? I assume if yes its the general uncertainty about how to model the callback judging from a quick look over the issues? I'm asking as I ran into a few annoyances in rewriting some markdown stuff in rust-analyzer due to the incorrect lifetimes.

**Comment by marcusklaas** [comment] 2021-04-06 12:58
Hey @Veykril,

Apologies for the delay in getting back to you. The master branch should be ready for use and it could be published as new point release. The reason that hasn't happened yet is that there was still an option to be explored where the callback function would be a type parameter (especially around code bloat and embedability). I hope to sort that out soon.
