### ISSUE TITLE
Underscore _ splits the text event boundaries - Questions

### ISSUE THREAD

**Issue by rbuckland** [raphlinus/pulldown-cmark#146] opened 2018-09-09 00:27 UTC
*Thanks* for the library. It looks to be very useful.

Attempting to use cmark for processing "emoji" `:smile:` entries in text, I found that the Event::Text(content) was bounded by the "_" underscore. 

For example, the markdown 

```
# heading
Some text and :white_check_mark: here.
```
will generate 3 text Events.

```
Event::Text 1 - "Some text and :white"
Event::Text 2 - "_check"
Event::Text 3 - "_mark: here."
```

The event splitting on the _, is this expected ? I can see (presume) that it is caused by [this line](https://github.com/google/pulldown-cmark/blob/master/src/parse.rs#L210) ```for &c in b"\x00\t\n\r_\\&*[!`<" {```

The `_` in the regex causes the splitting.

Because the events split up the emoji entry text, processing these becomes quite cumbersome.

**Questions**

1. Could this be configurable ?
  * I found the non-`pub` exposed `OPTION_FIRST_PASS` that could help, but it seems more internal. (it alters the regex)
2. Is there a commonmark "reason" that _ causes a text boundary ? (it must be `_emphasis_`)
3. 👍 for #117 - **Add support for backtracking** will enable processing on these event boundaries immensely easier.

**Comment by crawford** [comment] 2018-11-05 23:03
I just ran into this while working on [marker](https://github.com/crawford/marker). I'd prefer if I didn't have to call `get_offset()` in order to read the location of the parser (I have to dump out the location of errors). If the iterator was a tuple of `Event` and position, I could just make the iterator Peekable and use a little logic to consume multiple, adjacent `Text` events.

**Comment by raphlinus** [comment] 2018-11-06 01:57
The underscore splitting the text is by design, and essentially for performance reasons - there's no guarantee that text blocks are contiguous, and there are other cases where it really can't be avoided. Also, note that the [cmark reference parser](https://spec.commonmark.org/dingus/?text=a_b) will generate multiple text nodes in its AST, for similar reasons.

Probably the best idea I have is an iterator to iterator transform that coalesces text regions, either combining `&str` regions when they're contiguous in memory, or allocating (so using `Cow`) when not. This is something I would consider as an optional add-on. I'd also consider an option to turn it on, which would probably be more ergonomic.

An iterator of `(event, position)` tuples also sounds like a useful thing, probably better than calling `get_offset`. Maybe file a separate feature request issue, so it doesn't get lost in the shuffle of this one?

**Comment by marcusklaas** [comment] 2019-03-13 16:47
We already combine some text nodes when their ends meet exactly, but it's not guaranteed. I think we could look into this as a performance improvement.

**Comment by oberien** [comment] 2019-03-13 16:59
For this reason I implemented an Iterator wrapper, which concatenates consecutive text eventsin my application: https://github.com/oberien/heradoc/blob/master/src/frontend/concat.rs
 It uses the str_concat crate, which I wrote for this reason as well https://crates.io/crates/str_concat

**Comment by marcusklaas** [comment] 2019-03-18 15:21
I experimented with this a little bit, but since pulldown_cmark is pull based, it's generally not possible to merge subsequent text nodes during event generation since it won't be clear what the final type of the next event will be until it is pulled.

Indeed, it seems the best strategy is to wrap an offset iterator in a peekable and then merge sequences of adjacent text events, much like @oberien has done.

Not sure if this should be part of the crate or not. It can obviously be implemented using the public API, so it's not necessary, but if there's wide enough use for it, it may make sense including it. It could possibly speed up our own HTML generation.

**Comment by marcusklaas** [comment] 2019-06-02 11:25
Closing this as we cannot do better internally than a wrapper approach.

**Closed by marcusklaas** 2019-06-02 11:25 UTC

**Comment by andradei** [comment] 2019-06-24 20:54
So the solution is to avoid cases of `_multiple_underscores_`?
