### ISSUE TITLE
support optional directive syntax

### ISSUE THREAD

**Issue by diauweb** [raphlinus/pulldown-cmark#577] opened 2022-03-28 14:22 UTC
https://talk.commonmark.org/t/generic-directives-plugins-syntax/444

Though not a CommonMark syntax, Directives provided a generic and standard way to extend Markdown at low cost.
 Comparing to reusing code blocks, it provided expressive syntax to describe custom elements which can be placed in any position with metadata included.

Project using pulldown-cmark like mdBook will be benefited from this as they can add custom features easily and quickly with confidence

**Comment by Martin1887** [comment] 2023-05-07 10:21
Duplicate of #616.

**Closed by Martin1887** 2023-05-07 10:21 UTC
Labels: duplicate
